apiVersion: v1
kind: ServiceAccount
metadata:
  name: efs-csi-controller-sa
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::914401603085:role/AmazonEKS_EFS_CSI_DriverRole


---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-02f24544220072279
  directoryPerms: "777"
  # basePath: "/"
provisioner: efs.csi.aws.com

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02f24544220072279::fsap-06fb63fd43ca73758

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02f24544220072279::fsap-0b3f500b859b6e5af
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data-dir1/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data-dir1
    - name: persistent-storage-2
      mountPath: /data-dir2
    resources:
      requests:
        cpu: 256m
        memory: 256Mi
      limits:
        cpu: "2"
        memory: 2048Mi
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim
  - name: persistent-storage-2
    persistentVolumeClaim:
      claimName: efs-claim-2
